# Generated by Django 3.2.4 on 2021-06-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20210613_0125'),
        ('products', '0012_auto_20210613_0125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=50)),
                ('shippingPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateField()),
                ('isDelivered', models.BooleanField(default=False)),
                ('createdAt', models.DateField()),
                ('shippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userProfile.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnRegisterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('paidAt', models.DateField()),
                ('isDelivered', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
