# Generated by Django 3.2.4 on 2021-06-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210613_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unregisterorder',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='unregisterorder',
            name='totalPrice',
        ),
    ]
