# Generated by Django 3.2.4 on 2021-06-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210613_0125'),
        ('order', '0005_auto_20210613_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerorder',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='registerorder',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='registerorder',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='registerorder',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='registerorder',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='registerorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
