# Generated by Django 3.2.4 on 2021-06-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_registerorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerorder',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
