# Generated by Django 3.2.4 on 2021-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_registerorder_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unregisterorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
