# Generated by Django 3.2.4 on 2021-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('mrp_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('main_photo', models.ImageField(upload_to='product/<django.db.models.fields.CharField>')),
                ('photo1', models.ImageField(blank=True, upload_to='product/<django.db.models.fields.CharField>')),
                ('photo2', models.ImageField(blank=True, upload_to='product/<django.db.models.fields.CharField>')),
                ('photo3', models.ImageField(blank=True, upload_to='product/<django.db.models.fields.CharField>')),
                ('photo4', models.ImageField(blank=True, upload_to='product/<django.db.models.fields.CharField>')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=80)),
                ('uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
