# Generated by Django 3.2.4 on 2021-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
