# Generated by Django 3.2.4 on 2021-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210604_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('FASHION', 'Fashion'), ('MOBILE', 'Mobile'), ('LAPTOP', 'Laptop'), ('APPLICANCES', 'Applicances')], max_length=80),
        ),
    ]
