# Generated by Django 3.2.4 on 2021-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', (('TV', 'TV'), ('Speakers', 'Speakers'), ('Console', 'Console'), ('Accessories', 'Accessories'), ('Smartwatch', 'Smartwatch'))), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Applicances', 'Applicances')], max_length=80),
        ),
    ]
