# Generated by Django 3.2.4 on 2021-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Electronic', (('Laptop', 'Laptop'), ('Desktop', 'Destop'), ('Speakers', 'Speakers'), ('Console', 'Console'), ('Accessories', 'Accessories'), ('Smartwatch', 'Smartwatch'))), ('Fashion', (('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'))), ('Phone', (('Smartphone', 'Smartphone'), ('Keypad', 'Keypad'), ('Tablet', 'Tablet'))), ('Applicances', (('Washingmachince', 'Washingmachine'), ('TV', 'TV'), ('AC', 'AC'), ('KitchenApplicance', 'KitchenApplicance'), ('HomeApplicance', 'HomeApplicance')))], default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Fashion', 'Fashion'), ('Mobile', 'Mobile'), ('Applicances', 'Applicances')], max_length=80),
        ),
    ]
