# Generated by Django 3.2.4 on 2021-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210604_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
