# Generated by Django 3.2.4 on 2021-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210604_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('main_photo', models.ImageField(upload_to='product/')),
                ('category', models.CharField(choices=[('Electronic', 'Electronic'), ('Fashion', 'Fashion'), ('Mobile', 'Mobile'), ('Applicances', 'Applicances')], max_length=80)),
                ('subcategory', models.CharField(choices=[('Electronic', (('Laptop', 'Laptop'), ('Desktop', 'Destop'), ('Speakers', 'Speakers'), ('Console', 'Console'), ('Accessories', 'Accessories'), ('Smartwatch', 'Smartwatch'))), ('Fashion', (('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'))), ('Phone', (('Smartphone', 'Smartphone'), ('Keypad', 'Keypad'), ('Tablet', 'Tablet'))), ('Applicances', (('Washingmachince', 'Washingmachine'), ('TV', 'TV'), ('AC', 'AC'), ('KitchenApplicance', 'KitchenApplicance'), ('HomeApplicance', 'HomeApplicance')))], max_length=80)),
                ('uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
