# Generated by Django 3.2.4 on 2021-06-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_featurelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelisting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='isLaunched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='featurelisting',
            name='poster',
            field=models.ImageField(default=1, upload_to='product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='featurelisting',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
