# Generated by Django 3.2.4 on 2021-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210606_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
