# Generated by Django 3.2.4 on 2021-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelisting',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Electronic', (('Laptop', 'Laptop'), ('Desktop', 'Destop'), ('Speakers', 'Speakers'), ('Console', 'Console'), ('Accessories', 'Accessories'), ('Smartwatch', 'Smartwatch'))), ('Fashion', (('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'))), ('Phone', (('Smartphone', 'Smartphone'), ('Keypad', 'Keypad'), ('Tablet', 'Tablet'))), ('Applicances', (('Washingmachince', 'Washingmachine'), ('TV', 'TV'), ('AC', 'AC'), ('KitchenApplicance', 'KitchenApplicance'), ('HomeApplicance', 'HomeApplicance')))], max_length=80),
        ),
    ]
