# Generated by Django 3.2.4 on 2021-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_featurelisting_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=70)),
                ('mrp_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('poster', models.ImageField(blank=True, upload_to='product/')),
                ('main_photo', models.ImageField(upload_to='product/')),
                ('photo1', models.ImageField(blank=True, upload_to='product/')),
                ('photo2', models.ImageField(blank=True, upload_to='product/')),
                ('photo3', models.ImageField(blank=True, upload_to='product/')),
                ('photo4', models.ImageField(blank=True, upload_to='product/')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('Electronic', 'Electronic'), ('Fashion', 'Fashion'), ('Mobile', 'Mobile'), ('Applicances', 'Applicances')], max_length=80)),
                ('subcategory', models.CharField(choices=[('Electronic', (('Laptop', 'Laptop'), ('Desktop', 'Destop'), ('Speakers', 'Speakers'), ('Console', 'Console'), ('Accessories', 'Accessories'), ('Smartwatch', 'Smartwatch'))), ('Fashion', (('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'))), ('Phone', (('Smartphone', 'Smartphone'), ('Keypad', 'Keypad'), ('Tablet', 'Tablet'))), ('Applicances', (('Washingmachince', 'Washingmachine'), ('TV', 'TV'), ('AC', 'AC'), ('KitchenApplicance', 'KitchenApplicance'), ('HomeApplicance', 'HomeApplicance')))], max_length=80)),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('keywords', models.CharField(max_length=250)),
            ],
        ),
    ]
