# Generated by Django 3.2.4 on 2021-06-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_featureproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='mrp_price',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='title',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
            preserve_default=False,
        ),
    ]
