# Generated by Django 3.2.4 on 2021-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210613_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelisting',
            name='saleType',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Product', 'Product')], default='Sale', max_length=80),
        ),
    ]
